### ISSUE TITLE
C11 capacitor value

### ISSUE THREAD

**Issue by jsteel44** [borti4938/SNES_RGB_Bypass#2]
Do you mean 220nF? Seems the advice you link to suggests 300nF to 1uF.

https://github.com/borti4938/SNES_RGB_Bypass/blob/master/README.md?plain=1#L143

**Comment by borti4938** [comment]
Yes, I mean 220nF. It's a tradeoff between reduction of the ghosting effect and first line glitch (appearing if SNES changes brightness in $2100 register). See also https://shmups.system11.org/viewtopic.php?p=1286695#p1286695
